POST http://localhost:3000/api/assets
Content-Type: application/json

{
  "id": "asset2",
  "symbol": "A1"
}

###
GET http://localhost:3000/api/assets

###
GET http://localhost:3000/api/orders

###
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "asset_id": "asset2",
  "price": 120
}
